### ISSUE TITLE
构建时合并AndroidManifest.xml出现org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; 前言中不允许有内容

### ISSUE THREAD

**Issue by DuRunzhe** [Siy-Wu/ExcludeAar#4]
```
 Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processDevDebugManifest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
    ........  
Caused by: java.lang.RuntimeException: com.android.manifmerger.ManifestMerger2$MergeFailureException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; 前言中不允许有内容。
        at com.android.builder.core.AndroidBuilder.mergeManifestsForApplication(AndroidBuilder.java:548)
        at com.android.build.gradle.tasks.MergeManifests.doFullTaskAction(MergeManifests.java:173)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        ... 104 more
Caused by: com.android.manifmerger.ManifestMerger2$MergeFailureException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; 前言中不允许有内容。
        at com.android.manifmerger.ManifestMerger2.loadLibraries(ManifestMerger2.java:965)
        at com.android.manifmerger.ManifestMerger2.merge(ManifestMerger2.java:165)
        at com.android.manifmerger.ManifestMerger2.access$600(ManifestMerger2.java:61)
        at com.android.manifmerger.ManifestMerger2$Invoker.merge(ManifestMerger2.java:1542)
        at com.android.builder.core.AndroidBuilder.mergeManifestsForApplication(AndroidBuilder.java:508)
        ... 117 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; 前言中不允许有内容。
      
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1437)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
        at com.android.utils.PositionXmlParser.parse(PositionXmlParser.java:176)
        at com.android.utils.PositionXmlParser.parse(PositionXmlParser.java:139)
...

```
去除class的目的达到了，但是依赖之后无法正确构建打包

**Comment by Siy-Wu** [comment]
请问你的依赖type选择是那种？[图片]

**Comment by Siy-Wu** [comment]
/**
 * 调用依赖库的3种形式
 *
 */
enum TYPE {
    /**
     * 过滤类的jar包
     */
    JAR_EXCLUDE,
    /**
     * 过滤类的aar
     */
    AAR_EXCLUDE,

    /**
     * 工程依赖
     */
    PROJECT,
}

**Comment by ssiyy** [comment]
请你的依赖方式是那种，如果是JAR_EXCLUDE，就需要先运行一下mergeManifest这个task(注：运行合并AndroidManifest任务，必须要PROJECT依赖)把Android的清单文件合并一下啊。
注：配置依赖方式在dependencyConfig.gradle中

**Comment by DuRunzhe** [comment]
依赖的aar包，api project(path: ':xxxLib',configuration: 'exclude')，执行到任务app:processDevDebugManifest就会报这个错误，其中dev是我的一个产品风味

**Comment by Siy-Wu** [comment]
你项目如果是过滤aar包只需要只需要引入excludeAarr.gralde,如果需要过滤jar包只需要引入excludeJar.gradle，不要引入其他的脚本额

**Comment by ssiyy** [comment]
你项目如果是过滤aar包只需要只需要引入excludeAarr.gralde,如果需要过滤jar包只需要引入excludeJar.gradle，不要引入其他的脚本额。如果你只引入这2个脚本应该不会操作你的清单文件

**Comment by DuRunzhe** [comment]
只引入了excludeAarr.gralde，没有其他脚本，执行完excludeAar任务之后用api project(path: ':xxxLib',configuration: 'exclude')添加依赖
